# MongoDB database URI
database-uri: mongodb://127.0.0.1:27017/stprobe
# Socket.IO Session secret
session-secret: {very_secret}
# Interval in minutes
scan-interval: 2
# List of servers
servers:
- 17307 # Grupo GTD - Valdivia
- 939   # Telefónica Chile - Santiago
- 1779  # Comcast - Miami
